### PR TITLE
Pedro html

### PR DESCRIPTION
**Pull request by pedromorgan**
Tidy up web interface

### CODE REVIEW

**Comment by pedromorgan** [comment]
Screenshot_20190504_120557

**Comment by pedromorgan** [comment]
@npiganeau Am playing with the html interface, figuring out whats going on...

One snag is that i cant seem to get a "object/action" off a websocket response, eg
```
> SENT: {"object": "server", "action": "register", "params": {"type": "client", "token": "client-secret"}}
= RESPONSE: {"id":0,"msgType":"response",
   "data":{"status":"OK","message":"Successfully registered"}
}
```
it doesn't  repond with the object/action to round trip. I was expecting something like..
```
= RESPONSE: {"id":0,"msgType":"response",
    "data":{"object": "server", "action": "register", "status":"OK","message":"Successfully registered"}
}
```

Likewise.. expect
```
> SENT: {"object": "simulation", "action": "start"}
= RESPONSE: {"id":0,"msgType":"response",
 "data":{"object": "simulation", "action": "start, "status":"OK","message":"Simulation started successfully"}}
```

Or am i missing something ?
Lots of work in there though.. u been real busy ;-)

**Comment by pedromorgan** [comment]
What I'm trying to do is login, stop, start etc so I update interface based upon reply..

**Comment by npiganeau** [comment]
You should send an ID with your request. The response will have the same ID. That's how you make the link between a request and a response. Inspired by jsonrpc.

**Comment by pedromorgan** [comment]
Umm ok, but that wont work if i got say three clients attached, and one of them commands a stop..

**Comment by pedromorgan** [comment]
Screenshot_20190504_162432

**Comment by pedromorgan** [comment]
@npiganeau so after thinking, maybe just add new fields to Responses
```
// ResponseStatus is a status message sent to a websocket client
type ResponseStatus struct {
	ID      int         `json:"id"`
	MsgType MessageType `json:"msgType"`
       Object  string  `json:"object"`
       Action  string  `json:"action"`
	Data    DataStatus  `json:"data"`
}
```

**Comment by npiganeau** [comment]
Responses are sent only to the client that sent the command. Other clients should register to listeners to be notified. Here the "stateChanged" event is what you need.

**Comment by npiganeau** [comment]
Forgot to say: nice work on web interface!

**Comment by pedromorgan** [comment]
... guess u been busy on other things ;-)..
Lots of great work u done there.. (pats on back )..
but u started the whole thing anyway.. so am embelishing ;-)

@npiganeau Put me outta my misery.. what does this do ???
```
var _ hubObject = new(placeObject) // <<< why ???

func init() {
	hub.objects["place"] = new(placeObject)
}
```

**Comment by npiganeau** [comment]
It's just too check that *placeObject implements hubObject at compile time.

**Comment by pedromorgan** [comment]
@npiganeau moving issues here to https://github.com/ts2/ts2-sim-server/issues/13

**Comment by pedromorgan** [comment]
Screenshot_20190505_222225

**Comment by pedromorgan** [comment]
@npiganeau so have pushed the `pedro-html` branch so u can checkout easily..

Its works with 2 browsers, BUT, the steps are
- 1: open WS
- 2: Login which adds listeners also (stateChanged+clock)
- 3: Stop start at will

Snags...
- If a connection is dropped, the sim is still running, reconnecting again required, login etc+ listeners
- so am about to modify so as soon as client connects, its adds clock+stateChanged

Its kinda back to my original expectation, that the connection needs to "broadcast state+time", regardless of login..

Login is only required to manipulate imho, 

But it Works !!!!!!! ;-)))))))))))
ta @npiganeau

**Comment by pedromorgan** [comment]
Screenshot_20190507_125837

**Comment by pedromorgan** [comment]
@npiganeau Can u check, comments etc.... this is probably ready for merge.

**Comment by npiganeau** [comment]
@pedromorgan Overall I like it very much. 2 comments though:

1. CSS: 
  - The [X] button should probably have the same height as the input
  - The Clear button disappears when hovered
  - "Send & Clear" is more "Clear & Send" actually

2. Purpose of the webclient

I think we are mixing here two different purposes which are both good and should be kept, but maybe separetely:
- API testing, which is what the previous version did. Idea is to keep as close to WS JSON protocol so that the user can make tests and see the result of his actions.
- Web client, which is what you started to do and will eventually (I suppose) enable a user to play the sim through the browser, with SVG graphics and a lot of cool features. In this case the WS communication will progressively be hidden from the user.

For now, I **need** the first purpose of API testing and am **excited** to go towards the second purpose.

In the version of this PR, it could serve both purposes at once, except for the "list" menu of each object type which sends the request directly without the user to check and validate the JSON he is writing. So this lacks the ability of API testing.

Maybe you could keep the low level API testing (just about as it is now) in a back tab and put the higher level function you coded on the front page ?

**Comment by pedromorgan** [comment]
@npiganeau fixed the interface issues...

I've also removed the visibility of the "data.table" stuff (commented out code), so its lergely as before, apart from notifications in another tab (as clock makes a lot of noise)

So if its ok to merge this, in the meantime, am working on code to get the id's working with current schema, interface

**Pull request merged**
