### PR TITLE
pedro stufff !

### PR DESCRIPTION
**Pull request by pedromorgan**
mainly docs

### CODE REVIEW

**Comment by pedromorgan** [comment]
Bumping into interesting errors..

Had to fix the json data with "dealyGenerator" - https://github.com/ts2/ts2-sim-server/blob/pedro-dev/simulation/time_stuff.go#L49

and ROutes.initialize crashed() as BeginSignal() returns nil

**Comment by pedromorgan** [comment]
Ok have had a good look and hacked parts of the sim-server...

Mainly cos I'm trying to have a full understanding of whats happening, learning go, but things are clearer now (kinda ;-)).. but here and some Questions and Comments.

# Sim Json/Loading Issues

## Invalid Json for DelayGenerator

The sim in ts2-data/UK didn't load
- unless delayGenerator is tweaked https://github.com/ts2/ts2-sim-server/blob/pedro-dev/simulation/time_stuff.go#L49
- So this means either using patch, or fixing the data files upstream in ts2-data
- DelayGenerator is used in a few places.. so a good fix maybe necessary

## options load from ts2-data
- There is kinda typecase problem where stuff id incorrect

```
Version float <> "version": "2.3"
Version string <> "version": 2.3
//version could be "0.9.2-alpha"
TrackCircuitBased bool <> "trackCircuitBased": 0
```
- Fix for option is https://github.com/ts2/ts2-data/commit/8f90b807962ab371fd36e3b7cfda973207191361

## problems...

This leads to a few issues, and indeed and suprised how "stubborn" golang is, after years of python, but its an issue that aint gonna go away.

But root issue is probably the simple_json() which was "designed" for serialising objects in py.. so not 100% conform, convenience hack. We are not in py land anymore.. :confused: 

I prefer to go with a pathched up ts2-data, even if its manual.. at least we know "that right"...

And that leads to another issue of "test_data/demo.json"..
- I would prefer to stick all sim files in ts2-sims - so to add/modify sim u send patch
- and reassign ts2-data for the "static boring stuff", such as signals, lights, colors, etc
- but that is the way I see it.. What we want end users to have in the "data" about lights etc, and then go and create their sim around it.. instead of having to redefine things..

**Comment by pedromorgan** [comment]
# The Fun parts

Sorry @npiganeau and I hope u dont get "pissed off" with me.. but I like to rename things sometimes, and move things in files so its a nice target.. so apologies... but golang is no nice.. one can `git mv any.go things.go`

I'm just trying to make it obvious to a new dev, where things are likely to be.. 
- eg color stuff in a file and time.
- But looming is a larger issue on other stuff..

So I prefer to have a "known Intentin".. and some handt shortcults we can discuss
- in server/ I make H_\* we could make a handler
- H_HomePage

So As a server, I really really dont want nothing in there apart from code..
But at the end of the day its not php, or python so that means we need to embed assets in code.. or use a technichque to embed data.. anyway for now templates are in there.. and need as build.. with go-bindata

## Point, Switch, XOver
- I had to rename Direction to PointDirection... I was so confused if it was a "reversed" train.. etc.. 
- so all PointsItems == PointDirection
- So I kinda want rename now to PointState = Dead, Alive, *
- We need these as constants generated for client automatic. I think so

**Comment by pedromorgan** [comment]
Static and hot reload tempaltes

I dont want to many dependancies.. indeed not static assets .
- but we are stuck in that game..
- and indeed the arguments before of resource files.... argh..
- Main snag is debugging and hot reload, so that is whay I suggest we have dev/preview/live (same as interlock)
- so in fab build_dev is convenience to make these
- the idea at the monmet is that /templates/\* is a golang deplate and "all witihn"..
- step #1 = set up "relation" with go-bindata - debug
- step #2 = run and change html on every refresh

**Comment by pedromorgan** [comment]
# LIVE TV:

Amazing.. in last 30 mins....
- around 2 hours ago I put out trash.. in UK Blue=Recycle, and Green=Organic
- pat down.. and generally line up for "recycling+refuge collection"
- all ready with all others on every side of street
- BTW - yellow bags = medical disposal.. so u can see this,
- Tonite... Earlier..
  ... @pedromorgan looked around, with shadowns loking down..
  ... three people in yard... going through my bin..
  ... Yes its a cat.. NO.. 
  ... It a loose dog...
  ... loose dog NO
  ... Its a fox and her winter cubs..  amazing.. all two of them.. and mama and out and in asap..
  ... Need to take PIC for evidence.. whaw.. a farmers son.. as sly as a fox.. as they say.. 

# pedro-view on rats+fox+badgers+moles+snails+spiders
- They all work together..

**Comment by pedromorgan** [comment]
```
Once upon a time, on a cutting,
the young rail rabbits found their own ground,
they could chew thei little nibbles and get between the rails..
and as the train went pass they duck down.. and job done..
https://www.youtube.com/watch?v=fi-VH6mksEM
```

**Comment by npiganeau** [comment]
Quickly several things:
- Yes, v0.6 JSON (with string options) is not compatible with v0.7 sim server JSON. Agree with you, the new format is best. What I have in mind is:
  - v0.6 sim can read only v0.6 JSON version. Same with v0.6 editor (no backport). 
  - v0.7 editor can read either version but write only in new format (to be done: see developer TODO)
  - v0.7 game (i.e. sim-server for the time being) only read new format
- Splitting sims: to be discussed. Facts:
  - the sim-server will only accept a single JSON file with all the information into it to start a game.
  - we can imagine that this file is generated from several other files (sim + static data for instance):
    - either by the editor at sim creation time : rationale here is to say that one given sim will have its set of static data and that it makes no sense to change it at game time. But being able to create a sim from different libraries of static data is interesting. So the editor downloads the different static types it needs and create a single JSON file with everything in it uploaded to the data server (being ts2-sim or ts2-data, I don't care)
    - or by the sim launcher just before starting the game : this is more complicated because it implies a complex dependency system between sims and static data files so that the launcher knows what to download and concatenate in the JSON file for the sim-server. Also, you will need a versionning system for static data, 'cos if one sim depends on a static data on one version and that you change it, you may break the sim (thinking about signals for instance).
  
  So even if it's less 'cool' on the paper, I think I prefer the first option that is:
  - Static data libraries are available for sim writers and they can download them in the editor.
  - Simulation created by the editor contain the full JSON and do not depend on the static data libraries (sort of 'static library linking')
  - Simulations are uploaded by editor to the sim repo, downloaded by the sim launcher and forwarded to the sim-server (see NextArch diagram)
- There are lots of things in your code. Probably I don't agree with all of it, but I will go through it and merge the parts I like, and we can discuss the others.

**Comment by npiganeau** [comment]
Ok. I've done the review and imported some of them.
- Ajax: not imported. We only want websocket inside the core sim server. If we need ajax, then we'll make a proxy app.
- SVG: I want to have ts2 up and running before changing the way it works. So why not, but later on.
- HTML templates: home template will be the only template we'll have (since we only have websocket), so I keep it in the source file. Much simpler than having an extra dependency + specific build instructions. I use pycharm + go plugin which enables to do HTML language injection in the go source code, so I even have source highlighting. BTW, your new home page is cool !

**Comment by npiganeau** [comment]
Also, I did not import the Debug feature because the next step I want is to change logging library to use https://github.com/inconshreveable/log15 instead of `log`.

log15 enables to have context loggers and log levels (including debug level).

**Comment by pedromorgan** [comment]
I stuck the AJAX in to mainly debug loading etc... dont see any harm in having it as a down/dirty way to "look" at sim state..but anyway.. later..

**Comment by pedromorgan** [comment]
moot

**Comment by pedromorgan** [comment]
Lets go.. @npiganeau is sleping

**Pull request closed without merging**
